# Generated by Django 4.2 on 2025-01-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Brak opisu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='Domyślna kategoria', on_delete=django.db.models.deletion.CASCADE, to='events.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default='Brak lokalizacji', on_delete=django.db.models.deletion.CASCADE, to='events.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
