# Generated by Django 4.2 on 2025-01-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_delete_organizer_event_description_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Brak opisu'),
        ),
    ]
